; UI.Settings
class Settings extends UI.Base
{
    __New(title)
    {
        options := "+OwnDialogs +AlwaysOnTop"
        base.__New(title, options)
        this.Build()
    }

    Build()
    {
        this.Font := {options: "S12", fontName: ""}
        this.ApplyFont()
        this.Add("TreeView", "x8 y8 w160 h322")
        this.Add("GroupBox", "x176 y0 w434 h290", "<Field Name>")
        this.Add("GroupBox", "x184 y20 w417 h138 Section", "Field Info")
        this.Add("Edit", "xs+8 ys+20 w403 h113 +Multi +ReadOnly", "Text")
        this.Add("Text", "xs+8 ys+155 w100 h23 +0x200 +Right Section", "Current Value")
        this.Add("Edit", "x+8 ys+0 w298 h21 +ReadOnly", "Value")
        this.Add("Text", "xs+0 ys+40 w100 h23 +0x200 +Right Section", "Default Value")
        this.Add("Edit", "x+8 ys+0 w298 h21 +0x200 +ReadOnly", "Default")
        this.Add("Button", "xs+0 ys+32 w160 h30 Section", "&Restore Default")
        this.Add("Button", "x+138 ys+0 w110 h30", "&Edit Value")
        this.Add("Button", "xs+0 y296 w160 h30 Section", "Restore &All Defaults")
        this.Add("Button", "x+14 ys+0 w110 h30", "&Save")
        this.Add("Button", "x+14 ys+0 w110 h30", "&Cancel")
    }

    Show()
    {
        base.Show("w620 h336")
    }
}

; ; Generated by AutoGUI 2.5.8
; #SingleInstance Force
; #NoEnv
; SetWorkingDir %A_ScriptDir%
; SetBatchLines -1

; Gui Show, w620 h336, Window
; Return

; GuiEscape:
; GuiClose:
; ExitApp
