; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, TreeView, x8 y8 w160 h322
Gui Add, Text, x184 y176 w80 h23 +0x200 +Right, Current Value
Gui Add, Edit, x280 y176 w321 h21, Value
Gui Add, Text, x184 y216 w80 h23 +0x200 +Right, Default Value
Gui Add, GroupBox, x176 y0 w434 h281, GroupBox
Gui Add, Edit, x280 y216 w320 h21 +ReadOnly, Default
Gui Add, GroupBox, x184 y16 w417 h138, Field Info
Gui Add, Text, x192 y32 w403 h113, Text
Gui Add, Button, x472 y248 w129 h23, &Restore Default
Gui Add, Button, x184 y296 w129 h23, Restore &All Defaults
Gui Add, Button, x328 y296 w129 h23, &Save
Gui Add, Button, x472 y296 w129 h23, &Cancel

Gui Show, w620 h336, Window
Return

GuiEscape:
GuiClose:
    ExitApp
