
@startuml

skinparam LegendBackgroundColor #FAFAFA

start

:User Starts Installation Program;

:Select installation location;

if (Existing installation detected?) then (yes) 
  :Check version number;

  if (existing version = current version?) then (yes)
    stop
  else (no)
    :Find migrations for existing version;
    while (existing version < current version) is (true)
      :Perform migrations to next version;
      :Set existing version = next version;
    endwhile (false)
  endif
else (no)
  :Perform fresh install of current version;
endif

:Show installation complete screen;

stop

@enduml